//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.default_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Vector2 LeftJoystickVector2
        {
            get
            {
                return SteamVR_Actions.default_LeftJoystickVector2;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftJoystickPressed
        {
            get
            {
                return SteamVR_Actions.default_LeftJoystickPressed;
            }
        }
        
        public virtual SteamVR_Action_Vector2 RightJoystickVector2
        {
            get
            {
                return SteamVR_Actions.default_RightJoystickVector2;
            }
        }
        
        public virtual SteamVR_Action_Single LeftGrabTrigger
        {
            get
            {
                return SteamVR_Actions.default_LeftGrabTrigger;
            }
        }
        
        public virtual SteamVR_Action_Single RighttGrabTrigger
        {
            get
            {
                return SteamVR_Actions.default_RighttGrabTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftTopButton
        {
            get
            {
                return SteamVR_Actions.default_LeftTopButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftBottomButton
        {
            get
            {
                return SteamVR_Actions.default_LeftBottomButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightTopButton
        {
            get
            {
                return SteamVR_Actions.default_RightTopButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightBottomButton
        {
            get
            {
                return SteamVR_Actions.default_RightBottomButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftGrabBool
        {
            get
            {
                return SteamVR_Actions.default_LeftGrabBool;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightGrabBool
        {
            get
            {
                return SteamVR_Actions.default_RightGrabBool;
            }
        }
        
        public virtual SteamVR_Action_Single LeftPointerFingerTrigger
        {
            get
            {
                return SteamVR_Actions.default_LeftPointerFingerTrigger;
            }
        }
        
        public virtual SteamVR_Action_Single RightPointerFingerTrigger
        {
            get
            {
                return SteamVR_Actions.default_RightPointerFingerTrigger;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
